uploads = []
generated = []

[[outputs]]
id = "r64cHo07JJtST5rF6TPI0"
uri = "file://autoreport-hostinger.zip"
type = "unspecified"
title = "AutoReport — Hostinger FINAL (1.2 MB — build du 14 mai 2026)"
